---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

[An introductory vignette.](intro.html)

[MASH v FLASH simulation results.](MASHvFLASHsims.html) Compares MASH and FLASH fits to data simulated from MASH and FLASH models.

[MASH v FLASH detailed simulation study.](MASHvFLASHsims2.html) Compares the performance of MASH and FLASH on different covariance structures in a single simulation setting.

The next two analyses compare MASH and FLASH fits using datasets from the GTEx project.

* [MASH v FLASH analysis of GTEx data (strong tests).](MASHvFLASHgtex.html)

* [MASH v FLASH analysis of GTEx data (random tests).](MASHvFLASHrandom.html)

[MASH v FLASH workflows for GTEx.](MASHvFLASHgtex2.html) Proposes improved workflows to obtain MASH and FLASH fits to GTEx data. Describes the MASH fit and five different FLASH fits ("OHF", "Top 5", "Top 10", "Top 20", and "Zero") in detail.

Next up is a series of analyses that examine individual tests in an effort to identify salient differences among fits:

* [MASH v FLASH GTEx analysis: MASH v OHF.](MASHvOHF.html)

* [MASH v FLASH GTEx analysis: MASH v "Top 20".](MASHvTop20.html)

* [MASH v FLASH GTEx analysis: OHF v "Top 20".](OHFvTop20.html)

* [MASH v FLASH GTEx analysis: "Top 20" v "Zero".](Top20vZero.html)

* [Some conclusions.](conclusions.html)

Next, I experiment with putting nonnegative priors on loadings:

* [Nonnegative FLASH loadings.](MASHvFLASHnn.html) Uses nonnegative priors to obtain nicer data-driven loadings.

* [MASH v FLASH GTEx analysis: nonnegative loadings.](MASHvFLASHgtex3.html) Compares MASH and FLASH fits using the nonnegative data-driven loadings obtained in the previous analysis.

* [Fitting nonnegative loadings with a non-diagonal error covariance structure.](MASHvFLASHnondiagonalV.html) Uses the trick discussed [here](https://willwerscheid.github.io/FLASHvestigations/arbitraryV.html) to fit a non-diagonal $V$ and compares resulting loadings with those of previous analyses.
